### PR TITLE
add TVIP-AXI

### PR DESCRIPTION
**Pull request by taichi-ishitani**
Hi,

This PR is to add UVM based AMBA AXI4 VIP which I'm developing.
https://github.com/taichi-ishitani/tvip-axi

### CODE REVIEW

**Comment by umarcor** [comment]
I'm not sure about adding this as an isolated item. Coherently with the discussion in #201, both UVM and AXI4 are standards/specifications. Therefore, there are many different implementations of VIP or BFMs for them. I don't think it's sensible to overflow the items with several almost identical solutions. Instead, I'd like to have them listed together. 

Currently, there are no items for UVM or AXI4. Therefore, I would suggest adding one or both of them, and including TVIP-AXI in the references section. See, for instance, https://hdl.github.io/awesome/items/ghdl/.

As a complement, you might want to have TVIP-AXI added to https://www.librecores.org/.

**Comment by taichi-ishitani** [comment]
Hi @umarcor ,

Thanks for your comment!

> I'd like to have them listed together.

OK, I understand. How should we list meta information such as author name, license, etc.?
Like following?

* TVIP-AXI
  * Author
    * Taichi Ishitani
  * Link
    *  https://github.com/taichi-ishitani/tvip-axi
  * License
    * Apache License 2.0
* foo-vip
  *  Author
    * John Smith
 * Link
   * https://exmaple.com
* License
  *  MIT

**Comment by umarcor** [comment]
The main idea of having a series of references listed inside the body of an item such as UVM or AXI, is not to handle/track all the metadata of those references. Therefore, we don't need details such as the license, or the author name. I would just link to the repo/resource.

Alternatively, I think it would be nice to use a format similar to an academic citation, which would contain name/title, authors, year and URL in a single line per reference. I'd like to handle both papers and repos through bibtex (#185). This would provide a balance, as it would make more info machine-readable while showing limited content in the frontend. However, until that feature is implemented, it's ok to write it manually.

For having all the metadata about HDL libraries/cores, I strongly suggest using librecores. That's specific for searching/filtering reusable HDL code. This repo is for gathering tools in general. Hence, libraries for specific HDL's are a subset.

**Comment by taichi-ishitani** [comment]
Do you prefer notation like below? Is it correct?

```markdown
* [TVIP-AXI][1]

[1]: https://github.com/taichi-ishitani/tvip-axi "Taichi Ishitani, TVIP-AXI"
```
I don't know `BibTex` so I may  misunderstand what you want to say. If yes, I'd like you to show an sample format.

**Comment by umarcor** [comment]
The idea of bibtex/biblatex is to have a file with all the metadata and then select an specific style from printing it. Hence, there is not single bibtex style. I am used to the IEEE format: https://ieeeauthorcenter.ieee.org/wp-content/uploads/IEEE-Reference-Guide.pdf. In this case, I guess it would fall into "Manual (Online)". I'd propose the following:

> - T. Ishitani. *TVIP-AXI: AMBA AXI VIP*. [taichi-ishitani/tvip-axi](https://github.com/taichi-ishitani/tvip-axi)

**Comment by taichi-ishitani** [comment]
Thank you for your feedback!

> T. Ishitani. TVIP-AXI: AMBA AXI VIP. taichi-ishitani/tvip-axi

OK, I understand. I'm closing this PR and create a list of VIP/BFM for AMBA.

**Pull request closed without merging**
