### PR TITLE
Modified/expanded some categories

### PR DESCRIPTION
**Pull request by rodrigomelo9**
Related to #1 

Doubts:
* edalize and fusesoc are in the category "Tools:Package Managers"? In my opinion, edalize is a "Tools"Project Managers" or "Tools:Tool Managers". In case of fusesoc, it would be "Cores:Managers". 
* If there is a "Conferences" category, what about "Boards"?

### CODE REVIEW

**Comment by rodrigomelo9** [comment]
P&R seems not a valid name into config.yaml. "Tools:Place And Route"? "Tools:Placer"?

**Comment by eine** [comment]
As said in #1, I think it's ok to keep edalize and fusesoc in the same category, at least for now.

Yes, I think that a "Boards" category would be nice.

We can use "PnR" instead of "P&R", which is also commonly used (nextpnr, arachne-pnr...).

**Comment by eine** [comment]
The issue is with `"Tools"Programmers"`. It should be `"Tools:Programmers"`.

**Comment by eine** [comment]
Nice! It's ready for merging, isn't it?

**Comment by rodrigomelo9** [comment]
I think that it is ready. When needed we can add more categories.

**Pull request merged**
